name: OpenBB GitFlow

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  enforce_reviewers:
    runs-on: ubuntu-latest
    steps:
      # Check if the pull request has been approved and reviewed
      - name: Check if pull request has been approved and reviewed
        if: github.event.pull_request.reviews.total_count == 0 || github.event.pull_request.review.state != 'approved'
        run: exit 1

  check-branch-name:
    name: Enforce branch names on all branches.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Branch name: $GITHUB_REF"
          valid_branch_names=(
            "refs/heads/main"
            "refs/heads/develop"
            "refs/heads/release/\d+.\d+.\d+.*"
            "refs/heads/hotfix/*"
            "refs/heads/feature/*"
          )
          valid=false
          for pattern in "${valid_branch_names[@]}"; do
            if [[ "$GITHUB_REF" =~ $pattern ]]; then
              valid=true
              break
            fi
          done
          if $valid; then
            echo "Branch name is valid."
          else
            echo "Branch name is invalid."
            exit 1
          fi

  release-pr-restriction:
    name: Restrict any PRs to the release branch. Only allow PRs from the develop branch.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Branch name: $GITHUB_REF"
          if [[ "$GITHUB_REF" =~ "refs/heads/release/\d+.\d+.\d+.*" ]]; then
            echo "This is a release branch."
            if [[ "$GITHUB_BASE_REF" != "develop" ]]; then
              echo "This PR is not from the develop branch."
              exit 1
            fi
          fi